on: push

name: Integration

jobs:
 build:
  runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
      go-version: '1.18'
      cache: true
    - run: go run hello.go
    